### ISSUE TITLE
Multiple versions not supported

### ISSUE THREAD

**Issue by avirkar** [spring-projects/spring-hateoas-examples#26]
My API has two versions v1 / v2 and I am versioning the api using the uri. 
`endpoint version 1: https://mytestapi.test/api/v1/search`
`endpoint version 2: https://mytestapi.test/api/v2/search`
The response always has v1 in the self_link even if the request came for v2

```json
 {
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/api/v1/search/252f9d84-ea93-4234-887b-78e57ac6d730"
                    }
                },
                "id": "252f9d84-ea93-4234-887b-78e57ac6d730",
       
            }
```

**Comment by gregturn** [comment]
Do both versions/routes link to a single method?

You may wish to post your controller to reduce questions.

**Comment by avirkar** [comment]
Yes, Both of the version are part of the same controller, pointing to the same method. 

Controller: 

```Java
@RestController
@RequestMapping(value = {"/api/v1/search","/api/v2/search"},
                produces = MediaType.APPLICATION_JSON_VALUE)
@Validated
public class SearchController extends BaseController {

    @GetMapping
    @ResponseStatus(value = HttpStatus.OK)
    public ResponseEntity<PagedResources> getAll(
                    @PageableDefault(size = MAX_PER_PAGE) Pageable page,
                    PagedResourcesAssembler<Search> pagedAssembler, HttpServletRequest request) {

        Page<Search> items = environmentRepository.findAll(page);

        if (items == null || items.getTotalElements() == 0) {
            return new ResponseEntity<>(pagedAssembler.toEmptyResource(items, SearchResource.class, null), HttpStatus.OK);
        }

        SearchResourceAssembler assembler = new SearchResourceAssembler();
        return new ResponseEntity<>(pagedAssembler.toResource(items, assembler), HttpStatus.OK);

    }


}
```

Assembler:

```Java
public class SearchResourceAssembler implements ResourceAssembler<Search, SearchResource> {


    @Override
    public SearchResource toResource(Search model) {
        SearchResource resource = new SearchResource();


            resource.add(ControllerLinkBuilder.linkTo(methodOn(
                            SearchController.class).getSearchById(model.getId())).withSelfRel());


        return resource;
    }
}
```

**Comment by gregturn** [comment]
That's because `AnnotationMappingDiscoverer`, the lookup strategy for Spring MVC annotations, does this:

```java
	public String getMapping(Class<?> type) {

		Assert.notNull(type, "Type must not be null!");

		String[] mapping = getMappingFrom(findMergedAnnotation(type, annotationType));

		return mapping.length == 0 ? null : mapping[0];
	}
```

It checks if there is a mapping, and if so, grabs the first entry.

**Comment by avirkar** [comment]
This seems to be like a bug as it should pick up the respective path where the request is received. But until that is fixed or addressed, what options do I have? My API needs to have the version as a part of relative path. I tried to check if I can utilize the "ControllerLinkBuilder" class but apparently linkTo() only accepts a controller as a it's args.

**Comment by gregturn** [comment]
Spring MVC let’s you inject the servlet request so you could peek inside it to see if it’s v1 or v2 and edit the link manually.

**Comment by gregturn** [comment]
Here's the subtle challenge in solving this. If you're making a call (`/api/v1/search`) and trying to get back a `self` link (which would be `/api/v1/search`), then peeking at the web request can easily resolve with mapping you need.

But if you're building a link from a totally different location, e.g. `/api/v2/orders`, and wanting to provide a link over to `/api/v1/search`, then how does your `OrderController` know which version of the API to serve? It's intrinsic knowledge to know that everything is on **v1** or **v2**, or that only your Ordering system is on **v2**, but the rest is still on **v1**.

This implies that from a design perspective, it may make sense to actually break things up into two different methods, one for each route. The code may be identical, but the semantics are not. Kind of like when you're deciding in OO whether or not to reuse something polymorphically or not.

**Comment by avirkar** [comment]
I am trying to generate the self_link in response using the ResourceAssembler class. 
My code looks something like this, just unable to find how to use the "ControllerLinkBuilder" to generate the link that I want. 

```java

package com.ultimatesoftware.service.assemblers;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;
import org.springframework.hateoas.ResourceAssembler;
import org.springframework.hateoas.mvc.ControllerLinkBuilder;
import com.ultimatesoftware.domain.models.Search;
import com.ultimatesoftware.service.SearchController;
import com.ultimatesoftware.service.SearchControllerV2;
import com.ultimatesoftware.service.resources.SearchResource;

/**
 * A {@link ResourceAssembler} that converts a Tenant to a TenantResource.
 */
public class SearchResourceAssembler implements ResourceAssembler<Search, SearchResource> {


    private String apiVersionString;

    public String getApiVersionString() {
        return apiVersionString;
    }


    public void setApiVersionString(String apiVersionString) {
        this.apiVersionString = apiVersionString;
    }


    public SearchResourceAssembler(String apiVersionString) {
        this.apiVersionString = apiVersionString;
    }


    @Override
    public SearchResource toResource(Search model) {
        SearchResource resource = new SearchResource();

        resource.setSearchId(model.getId());
        resource.setName(model.getName());
        resource.setCode(model.getCode());
        resource.setPermissions(model.getPermissions());


        if (apiVersionString.equals("/api/v1/search")) {
            **resource.add(ControllerLinkBuilder.linkTo(methodOn(
                            SearchController.class).getSearchById(model.getId())).withSelfRel());**

        } else {
            **resource.add(ControllerLinkBuilder.linkTo(methodOn(
                            SearchControllerV2.class).getSearchById(model.getId())).withSelfRel());**

        }


        return resource;
    }
}

```

**Comment by gregturn** [comment]
The proper to _now_ use is either `WebMvcLinkBuilder` or `WebFluxLinkBuilder`. `ControllerLinkBuilder` has been deprecated. 

Other than that, yeah that looks about right. Knowing when to pick a particular version is really based on your domain and hard to embed into framework code.

Now it's possible to put the `if-then` code somewhere else, but unless `SearchController` and `SearchControllerV2` share inheritance, your ability to use the IDE for method completion (`getSearchById`) won't be there. So indeed, if you must implement versions, what you've got is about right.

**Comment by gregturn** [comment]
One thing I would do it static imports for `linkto`, just like you did for `methodOn`.

**Comment by avivmu** [comment]
@gregturn Can we close this?
