### ISSUE TITLE
Wrong link created in https://github.com/spring-projects/spring-hateoas-examples/tree/master/hypermedia

### ISSUE THREAD

**Issue by thesse1** [spring-projects/spring-hateoas-examples#29]
The self link generated for GET http://localhost:8080/managers/1/employees is wrong:

        "self": {
            "href": "http://localhost:8080/employees"
        },

This points to the list of all employees, not just the employees of manager 1.

What is the best way to fix this? Maybe add another EmployeeRepresentationModelAssembler that does not simply add the self link by calling

             super.addLinks(resources);

but that extracts the manager id from the manager one of its content’s members? (By design, they must all have the same manager.) But what if the manager does not (yet) have any employees? Then we would not be able to reconstruct the manager’s id from the empty list of his emplyoees.

Very ugly… Is there a better way for this?

Maybe this: In the /managers/{id}/employees route in the EmployeeController, overload the addlinks method in EmployeeRepresentationModelAssembler by one that returns the correct link with the manager’s id?

	@GetMapping("/managers/{id}/employees")
	public ResponseEntity<CollectionModel<EntityModel<Employee>>> findEmployees(@PathVariable long id) {
		
		EmployeeRepresentationModelAssembler assemblerByManager = new EmployeeRepresentationModelAssembler() {
			@Override
			public void addLinks(CollectionModel<EntityModel<Employee>> resources) {
				resources.add(linkTo(methodOn(EmployeeController.class).findEmployees(id)).withSelfRel());
				resources.add(linkTo(methodOn(EmployeeController.class).findAll()).withRel("employees"));
				resources.add(linkTo(methodOn(EmployeeController.class).findAllDetailedEmployees()).withRel("detailedEmployees"));
				resources.add(linkTo(methodOn(ManagerController.class).findAll()).withRel("managers"));
				resources.add(linkTo(methodOn(RootController.class).root()).withRel("root"));
			}
		};
		
		CollectionModel<EntityModel<Employee>> resources = assemblerByManager.toCollectionModel(repository.findByManagerId(id));

		return ResponseEntity.ok(resources);
	}

Would that be OK? Is it OK to create our own instances of EmployeeRepresentationModelAssembler? Or should we always use one of the assembler instances injected by the Spring framework?

**Comment by gregturn** [comment]
@thesse1 See my proposed solution.

Since the issue is very contextual to the controller method, I figured that's the place to tweak the `CollectionModel` before it gets sent out for rendering.

**Comment by thesse1** [comment]
That's better, thanks! I was also looking for a way to replace an existing link in an existing model. It seems this is not possible, but I learned now that it is easy to create a new model based on an existing model, just with another set of links. Thanks!

**Comment by gregturn** [comment]
Check out the Links API. Ollie added some very handy stuff there recently.
