### ISSUE TITLE
commons:SimpleIdentifiableResourceAssembler.java getBasePath() is undefined

### ISSUE THREAD

**Issue by Fninth** [spring-projects/spring-hateoas-examples#9]
The method `getBasePath()` is undefined for the type `SimpleIdentifiableResourceAssembler<T>`
 line 128

**Comment by gregturn** [comment]
How are you building the project? I have it using Project Lombok, which either Maven or IntelliJ will generate the getters based on the `@Getter` annotation.

**Comment by Fninth** [comment]
I think lombok undermines the readability and integrity of the source code file, and I'll try to remove it next, thanks for your answer.
